build:
  cargo component build --workspace --release

compose:
  wasm-tools compose -c config.yml -o ../../aggregate.wasm ../../../target/wasm32-wasi/release/aggregate_wit_ui.wasm 

run: build compose

preview: run
  cd ../../sveltekit/ && npm run build && npm run preview -- --open
