// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
pub mod component {
  pub mod math {
    
    #[allow(clippy::all)]
    pub mod addition {
      #[used]
      #[doc(hidden)]
      #[cfg(target_arch = "wasm32")]
      static __FORCE_SECTION_REF: fn() = super::super::super::__link_section;
      #[allow(unused_unsafe, clippy::all)]
      pub fn add(x: i32,y: i32,) -> i32{
        
        #[allow(unused_imports)]
        use wit_bindgen::rt::{alloc, vec::Vec, string::String};
        unsafe {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "component:math/addition@0.1.0")]
          extern "C" {
            #[link_name = "add"]
            fn wit_import(_: i32, _: i32, ) -> i32;
          }
          
          #[cfg(not(target_arch = "wasm32"))]
          fn wit_import(_: i32, _: i32, ) -> i32{ unreachable!() }
          let ret = wit_import(wit_bindgen::rt::as_i32(x), wit_bindgen::rt::as_i32(y));
          ret
        }
      }
      
    }
    
  }
}
pub mod exports {
  pub mod example {
    pub mod calculator {
      
      #[allow(clippy::all)]
      pub mod calculate {
        #[used]
        #[doc(hidden)]
        #[cfg(target_arch = "wasm32")]
        static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_section;
        const _: () = {
          
          #[doc(hidden)]
          #[export_name = "example:calculator/calculate#evaluate"]
          #[allow(non_snake_case)]
          unsafe extern "C" fn __export_evaluate(arg0: i32,arg1: i32,) -> i32 {
            #[allow(unused_imports)]
            use wit_bindgen::rt::{alloc, vec::Vec, string::String};
            
            // Before executing any other code, use this function to run all static
            // constructors, if they have not yet been run. This is a hack required
            // to work around wasi-libc ctors calling import functions to initialize
            // the environment.
            //
            // This functionality will be removed once rust 1.69.0 is stable, at which
            // point wasi-libc will no longer have this behavior.
            //
            // See
            // https://github.com/bytecodealliance/preview2-prototyping/issues/99
            // for more details.
            #[cfg(target_arch="wasm32")]
            wit_bindgen::rt::run_ctors_once();
            
            let len0 = arg1 as usize;
            let bytes0 = Vec::from_raw_parts(arg0 as *mut _, len0, len0);
            let result1 = <_GuestImpl as Guest>::evaluate(wit_bindgen::rt::string_lift(bytes0));
            wit_bindgen::rt::as_i32(result1)
          }
        };
        use super::super::super::super::super::Component as _GuestImpl;
        pub trait Guest {
          fn evaluate(expr: wit_bindgen::rt::string::String,) -> i32;
        }
        
      }
      
    }
  }
}

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:calculator"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 370] = [3, 0, 10, 99, 97, 108, 99, 117, 108, 97, 116, 111, 114, 0, 97, 115, 109, 13, 0, 1, 0, 7, 63, 1, 65, 2, 1, 66, 2, 1, 64, 1, 4, 101, 120, 112, 114, 115, 0, 122, 4, 0, 8, 101, 118, 97, 108, 117, 97, 116, 101, 1, 0, 4, 1, 28, 101, 120, 97, 109, 112, 108, 101, 58, 99, 97, 108, 99, 117, 108, 97, 116, 111, 114, 47, 99, 97, 108, 99, 117, 108, 97, 116, 101, 5, 0, 11, 15, 1, 0, 9, 99, 97, 108, 99, 117, 108, 97, 116, 101, 3, 0, 0, 7, 156, 1, 1, 65, 2, 1, 65, 4, 1, 66, 2, 1, 64, 2, 1, 120, 122, 1, 121, 122, 0, 122, 4, 0, 3, 97, 100, 100, 1, 0, 3, 1, 29, 99, 111, 109, 112, 111, 110, 101, 110, 116, 58, 109, 97, 116, 104, 47, 97, 100, 100, 105, 116, 105, 111, 110, 64, 48, 46, 49, 46, 48, 5, 0, 1, 66, 2, 1, 64, 1, 4, 101, 120, 112, 114, 115, 0, 122, 4, 0, 8, 101, 118, 97, 108, 117, 97, 116, 101, 1, 0, 4, 1, 28, 101, 120, 97, 109, 112, 108, 101, 58, 99, 97, 108, 99, 117, 108, 97, 116, 111, 114, 47, 99, 97, 108, 99, 117, 108, 97, 116, 101, 5, 1, 4, 1, 29, 101, 120, 97, 109, 112, 108, 101, 58, 99, 97, 108, 99, 117, 108, 97, 116, 111, 114, 47, 99, 97, 108, 99, 117, 108, 97, 116, 111, 114, 4, 0, 11, 16, 1, 0, 10, 99, 97, 108, 99, 117, 108, 97, 116, 111, 114, 3, 2, 0, 0, 16, 12, 112, 97, 99, 107, 97, 103, 101, 45, 100, 111, 99, 115, 0, 123, 125, 0, 70, 9, 112, 114, 111, 100, 117, 99, 101, 114, 115, 1, 12, 112, 114, 111, 99, 101, 115, 115, 101, 100, 45, 98, 121, 2, 13, 119, 105, 116, 45, 99, 111, 109, 112, 111, 110, 101, 110, 116, 6, 48, 46, 49, 56, 46, 50, 16, 119, 105, 116, 45, 98, 105, 110, 100, 103, 101, 110, 45, 114, 117, 115, 116, 6, 48, 46, 49, 54, 46, 48];

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_section() {}
