package component:edwards-wit;

/// WIT interface exported by yourworld 
interface operations {
    sign: func(message: list<u8>) -> result<list<u8>, string>;
    verify: func(message: list<u8>, signature: list<u8>) -> result<bool, string>;
}

/// An example world for the component to target.
world example {
    import seed-keeper:wallet/seed-getter@0.1.0;
    export operations;
}
