[package]
name = "seed-keeper-events"
version.workspace = true
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
wurbo = "0.4.1" 
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.6.0", features = ["base64"] }
