interface types {
    /// The confuration of the seed keeper
    record credentials {
        /// The username to use for the seed keeper
        username: list<u8>,

        /// The password to use for the seed keeper
        password: list<u8>,

        /// Optional prevously generated encrypted seed to use for the seed keeper
        encrypted: option<list<u8>>
    }
}

