// None of the deps can have the same package name as this package, it conflicts. So we need to keep changing namespaces.
package wallet:aggregate-wit-ui@0.1.0;

interface aggregation {
  // calls activate on on the child components
  activates: func();
}

/// An example world for the component to target.
world example {
    // requests to the DOM via jco
    import wurbo-in;

    import seed-keeper:wit-ui/wurbo-out@0.1.0;
  
    // edwards-wit-ui wurbo-out
    import example:edwards-ui/wurbo-out@0.1.0;

    // requests from the DOM via jco
    export wurbo-out;

    export aggregation;
}
