package example:edwards-ui@0.1.0;

interface wurbo-out {

  use wurbo-types.{context};

  // renders the initial Web component with the given data
  render: func(ctx: context) -> result<string, string>;

  // activate listening 
  activate: func();
}
