package example:edwards-ui@0.1.0;

interface wurbo-out {

  use wurbo-types.{context};

  // renders the initial Web component with the given data
  // and the target template to use as top level entry point
  render: func(ctx: context) -> result<string, string>;

  // listen on all or given selectors
  activate: func(selectors: option<list<string>>);
}
