package seed-keeper:wit-ui@0.1.0;

/// An example world for the component to target.
world seedworld {
  import component:wallet/encrypted@0.1.0;
  import component:wallet/config@0.1.0;

  import wurbo-in;
  export wurbo-out;
}
